[package]
name = "misc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.18"
color-eyre = "0.6.2"
sporker = { version = "0.2.0", path = "../sporker" }
tokio = "1.21.2"
