[package]
name = "misc"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.18"
color-eyre = "0.6.2"
rusqlite = "0.36.0"
sporker = { path = "../sporker" }
tokio = "1.45.1"
