[package]
name = "sporker"
version = "0.4.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
rusqlite = "0.36.0"
thiserror = "2.0.12"
