[package]
name = "sporker"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
rusqlite = "0.29.0"
thiserror = "1.0.37"
